name: "🐞 오류"
description: "Fix"
labels: "🐞 오류"
body:
  - type: textarea
    attributes:
      label: "📌 설명"
      description: "오류에 대한 설명을 적어주세요."
      placeholder: "- 설명"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "📝 작업 내용"
      description: "오류를 해결하기 위한 작업 내용을 작성해 주세요!"
      placeholder: "- [ ] 작업 내용"
    validations:
      required: true